# Generated by Django 6.0.2 on 2026-02-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_password_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name_plural': 'Horarios'},
        ),
    ]
