# Generated by Django 6.0.2 on 2026-02-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_latitud_asistencia_latitud_real_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='perimetro',
            options={'verbose_name_plural': 'Perímetros'},
        ),
    ]
